//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(void);
void function_4000b0(void);
int32_t function_4000b4(int32_t a1, int32_t a2);
void function_40011c(void);
int32_t function_40013c(void);
int32_t function_4001f4(void);
int32_t function_400220(void);
void function_400350(void);
void function_40035c(void);

// --------------------- Global Variables ---------------------

int32_t g1 = -0x21524ff5; // 0x410360
int32_t g2 = -0x21524542; // 0x410364
int32_t g3 = -0x4ff40532; // 0x410368
int32_t g4 = 0x400b400b; // 0x41036c
int32_t g5 = 0x41414141; // 0x410370
int32_t g6 = 0x42424242; // 0x410374
int32_t g7 = 0x44444444; // 0x410378
int32_t g8 = 0x43434343; // 0x41037c
char * g9; // 0x410490

// ------------------------ Functions -------------------------

// Address range: 0x4000b0 - 0x4000b3
void function_4000b0(void) {
    // 0x4000b0
    return;
}

// Address range: 0x4000b4 - 0x40011b
int32_t function_4000b4(int32_t a1, int32_t a2) {
    int32_t * v1 = (int32_t *)(4 * a1 + (int32_t)&g1); // 0x4000c4_0
    uint32_t v2 = *v1; // 0x4000c4
    int32_t v3 = 0; // 0x4000e8
    uint32_t v4 = 0;
    // branch -> 0x4000d0
    int32_t v5; // 0x40010c
    while (true) {
        // 0x4000d0
        v5 = v3;
        if ((1 << v4 & a2) != 0) {
            // 0x4000dc
            v5 = (v2 >> v4 ^ v3) % 2;
            // branch -> 0x4000f0
        }
        // 0x4000f0
        if (v4 == 31) {
            // break -> 0x4000fc
            break;
        }
        v3 = v5;
        v4++;
        // continue -> 0x4000d0
    }
    int32_t result = 0x80000000 * v5; // 0x40010c
    *v1 = v2 / 2 | result;
    return result;
}

// Address range: 0x40011c - 0x40013b
void function_40011c(void) {
    // 0x40011c
    write(1, "gg\n", 4);
}

// Address range: 0x40013c - 0x4001f3
int32_t function_40013c(void) {
    // 0x40013c
    return g1 == -0xb3f4014 & g2 == 0x677c68fe & g3 == 0x36be477f & g4 == -0x37a7829f & g5 == 0x5ea2ba26 & g6 == -0xbf6ecfb & g7 == 0x44444444 & g8 == 0x140f46e;
}

// Address range: 0x4001f4 - 0x40021f
int32_t function_4001f4(void) {
    // 0x4001f4
    return read(0, (char *)&g9, 32);
}

// Address range: 0x400220 - 0x400293
// Used cryptographic patterns:
//  - AES_Rijndael_S___ARIA_S1 (8-bit, little endian)
int32_t function_400220(void) {
    char v1 = *(char *)&g9; // 0x4002383
    char v2 = *(char *)((int32_t)v1 % 256 + (int32_t)"\x63\x7c\x77\x7b\xf2\x6b\x6f\xc5\x30\x01\x67\x2b\xfe\xd7\xab\x76\xca\x82\xc9\x7d\xfa\x59\x47\xf0\xad\xd4\xa2\xaf\x9c\xa4\x72\xc0\xb7\xfd\x93\x26\x36\x3f\xf7\xcc\x34\xa5\xe5\xf1\x71\xd8\x31\x15\x04\xc7\x23\xc3\x18\x96\x05\x9a\x07\x12\x80\xe2\xeb\x27\xb2\x75\x09\x83\x2c\x1a\x1b\x6e\x5a\xa0\x52\x3b\xd6\xb3\x29\xe3\x2f\x84\x53\xd1\x00\xed\x20\xfc\xb1\x5b\x6a\xcb\xbe\x39\x4a\x4c\x58\xcf\xd0\xef\xaa\xfb\x43\x4d\x33\x85\x45\xf9\x02\x7f\x50\x3c\x9f\xa8\x51\xa3\x40\x8f\x92\x9d\x38\xf5\xbc\xb6\xda\x21\x10\xff\xf3\xd2\xcd\x0c\x13\xec\x5f\x97\x44\x17\xc4\xa7\x7e\x3d\x64\x5d\x19\x73\x60\x81\x4f\xdc\x22\x2a\x90\x88\x46\xee\xb8\x14\xde\x5e\x0b\xdb\xe0\x32\x3a\x0a\x49\x06\x24\x5c\xc2\xd3\xac\x62\x91\x95\xe4\x79\xe7\xc8\x37\x6d\x8d\xd5\x4e\xa9\x6c\x56\xf4\xea\x65\x7a\xae\x08\xba\x78\x25\x2e\x1c\xa6\xb4\xc6\xe8\xdd\x74\x1f\x4b\xbd\x8b\x8a\x70\x3e\xb5\x66\x48\x03\xf6\x0e\x61\x35\x57\xb9\x86\xc1\x1d\x9e\xe1\xf8\x98\x11\x69\xd9\x8e\x94\x9b\x1e\x87\xe9\xce\x55\x28\xdf\x8c\xa1\x89\x0d\xbf\xe6\x42\x68\x41\x99\x2d\x0f\xb0\x54\xbb\x16"); // 0x4002708
    *(char *)&g9 = v2;
    char * v3 = (char *)(1 + (int32_t)&g9); // 0x400238_0
    *v3 = *(char *)((int32_t)*v3 % 256 + (int32_t)"\x63\x7c\x77\x7b\xf2\x6b\x6f\xc5\x30\x01\x67\x2b\xfe\xd7\xab\x76\xca\x82\xc9\x7d\xfa\x59\x47\xf0\xad\xd4\xa2\xaf\x9c\xa4\x72\xc0\xb7\xfd\x93\x26\x36\x3f\xf7\xcc\x34\xa5\xe5\xf1\x71\xd8\x31\x15\x04\xc7\x23\xc3\x18\x96\x05\x9a\x07\x12\x80\xe2\xeb\x27\xb2\x75\x09\x83\x2c\x1a\x1b\x6e\x5a\xa0\x52\x3b\xd6\xb3\x29\xe3\x2f\x84\x53\xd1\x00\xed\x20\xfc\xb1\x5b\x6a\xcb\xbe\x39\x4a\x4c\x58\xcf\xd0\xef\xaa\xfb\x43\x4d\x33\x85\x45\xf9\x02\x7f\x50\x3c\x9f\xa8\x51\xa3\x40\x8f\x92\x9d\x38\xf5\xbc\xb6\xda\x21\x10\xff\xf3\xd2\xcd\x0c\x13\xec\x5f\x97\x44\x17\xc4\xa7\x7e\x3d\x64\x5d\x19\x73\x60\x81\x4f\xdc\x22\x2a\x90\x88\x46\xee\xb8\x14\xde\x5e\x0b\xdb\xe0\x32\x3a\x0a\x49\x06\x24\x5c\xc2\xd3\xac\x62\x91\x95\xe4\x79\xe7\xc8\x37\x6d\x8d\xd5\x4e\xa9\x6c\x56\xf4\xea\x65\x7a\xae\x08\xba\x78\x25\x2e\x1c\xa6\xb4\xc6\xe8\xdd\x74\x1f\x4b\xbd\x8b\x8a\x70\x3e\xb5\x66\x48\x03\xf6\x0e\x61\x35\x57\xb9\x86\xc1\x1d\x9e\xe1\xf8\x98\x11\x69\xd9\x8e\x94\x9b\x1e\x87\xe9\xce\x55\x28\xdf\x8c\xa1\x89\x0d\xbf\xe6\x42\x68\x41\x99\x2d\x0f\xb0\x54\xbb\x16");
    int32_t v4 = 2; // 0x40027c
    // branch -> 0x400234
    while (v4 != 32) {
        // 0x400234
        // 0x400234
        v3 = (char *)(v4 + (int32_t)&g9);
        *v3 = *(char *)((int32_t)*v3 % 256 + (int32_t)"\x63\x7c\x77\x7b\xf2\x6b\x6f\xc5\x30\x01\x67\x2b\xfe\xd7\xab\x76\xca\x82\xc9\x7d\xfa\x59\x47\xf0\xad\xd4\xa2\xaf\x9c\xa4\x72\xc0\xb7\xfd\x93\x26\x36\x3f\xf7\xcc\x34\xa5\xe5\xf1\x71\xd8\x31\x15\x04\xc7\x23\xc3\x18\x96\x05\x9a\x07\x12\x80\xe2\xeb\x27\xb2\x75\x09\x83\x2c\x1a\x1b\x6e\x5a\xa0\x52\x3b\xd6\xb3\x29\xe3\x2f\x84\x53\xd1\x00\xed\x20\xfc\xb1\x5b\x6a\xcb\xbe\x39\x4a\x4c\x58\xcf\xd0\xef\xaa\xfb\x43\x4d\x33\x85\x45\xf9\x02\x7f\x50\x3c\x9f\xa8\x51\xa3\x40\x8f\x92\x9d\x38\xf5\xbc\xb6\xda\x21\x10\xff\xf3\xd2\xcd\x0c\x13\xec\x5f\x97\x44\x17\xc4\xa7\x7e\x3d\x64\x5d\x19\x73\x60\x81\x4f\xdc\x22\x2a\x90\x88\x46\xee\xb8\x14\xde\x5e\x0b\xdb\xe0\x32\x3a\x0a\x49\x06\x24\x5c\xc2\xd3\xac\x62\x91\x95\xe4\x79\xe7\xc8\x37\x6d\x8d\xd5\x4e\xa9\x6c\x56\xf4\xea\x65\x7a\xae\x08\xba\x78\x25\x2e\x1c\xa6\xb4\xc6\xe8\xdd\x74\x1f\x4b\xbd\x8b\x8a\x70\x3e\xb5\x66\x48\x03\xf6\x0e\x61\x35\x57\xb9\x86\xc1\x1d\x9e\xe1\xf8\x98\x11\x69\xd9\x8e\x94\x9b\x1e\x87\xe9\xce\x55\x28\xdf\x8c\xa1\x89\x0d\xbf\xe6\x42\x68\x41\x99\x2d\x0f\xb0\x54\xbb\x16");
        v4++;
        // branch -> 0x400234
    }
    // 0x400288
    return (int32_t)&g9;
}

// Address range: 0x400294 - 0x40034f
int32_t main(void) {
    // 0x400294
    function_4001f4();
    function_400220();
    int32_t v1 = 0; // $s1
    // branch -> 0x4002a8
    while (true) {
        int32_t v2 = 0; // 0x4002b4
        function_4000b4(v2, *(int32_t *)(4 * v2 + (int32_t)&g9));
        int32_t v3 = 1; // 0x4002c8
        // branch -> 0x4002ac
        while (v3 != 8) {
            // 0x4002ac
            v2 = v3;
            function_4000b4(v2, *(int32_t *)(4 * v2 + (int32_t)&g9));
            v3++;
            // continue -> 0x4002ac
        }
        int32_t v4 = g5;
        g5 = g1;
        g1 = v4;
        int32_t v5 = g3; // 0x4002f4
        g3 = g2;
        g2 = v5;
        int32_t v6 = g7; // 0x400304
        g7 = g8;
        g8 = v6;
        int32_t v7 = g6; // 0x400314
        g6 = g4;
        g4 = v7;
        int32_t v8 = v1 + 1; // 0x400320
        v1 = v8;
        if (v8 == 32) {
            // break -> 0x40032c
            break;
        }
        // continue -> 0x4002a8
    }
    int32_t result = function_40013c(); // 0x400330
    if (result == 0) {
        // 0x40033c
        function_400350();
        // branch -> 0x400348
    }
    // 0x400348
    function_40011c();
    return result;
}

// Address range: 0x400350 - 0x40035b
void function_400350(void) {
    // 0x400350
    exit(99);
    // UNREACHABLE
}

// Address range: 0x40035c - 0x40035f
void function_40035c(void) {
    // 0x40035c
    return;
}

// ------------------ System-Call Functions -------------------

// void exit(int status);
// ssize_t read(int fd, void * buf, size_t nbytes);
// ssize_t write(int fd, const void * buf, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: upx (3.09)
// Detected functions: 9
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-02-03 19:29:56
